### ISSUE TITLE
byshape integration branch

### ISSUE THREAD

**Issue by JATothrim** [nsch0e/opencubes#12]
@nsch0e You seem to be currently directly pushing into byshape branch your changes and
this makes any work that I'll (and others) attempt on that branch very hard to integrate.

Could keep the byshape branch as "integration branch" that will receive your work and all others only as pull requests?
You could then do your changes on your work branch, publish it once that branch is in good state.
This way we can see review changes before merging them onto byshape.

**Comment by nsch0e** [comment]
Will do. I force pushed first b/c of the convoluted git history. The other two pushes were to get it into a workable state. I considered the previous state unfriendly for others (e.g. you) to work with. the current state behaves more or less as main, so for any further improvements i will make PRs onto byshape.

**Comment by nsch0e** [comment]
@JATothrim When is the point when I should merge a PR. As I understand it this means every open PR to byshape should rebase then.
Advantage of the PRs is "just" that I don't push unreviewed changes which contaminate byshape?

**Comment by JATothrim** [comment]
> @JATothrim When is the point when I should merge a PR. As I understand it this means every open PR to byshape should rebase then. Advantage of the PRs is "just" that I don't push unreviewed changes which contaminate byshape?

Good point. 
When to merge PRs: as soon as they are complete and don't break things. (byshape_fixes at moment is good)
PRs should be merged in order that makes resolving conflicts easier.  Thats about it.

When you merge PRs from other repo(s) onto byshape, you should rebase work branch onto the updated byshape. So every PR  is rebased onto byshape before it is made public.
See: [Rebase vs. Merge](https://stackoverflow.com/questions/804115/when-do-you-use-git-rebase-instead-of-git-merge)
