### ISSUE TITLE
split cache file bug

### ISSUE THREAD

**Issue by JATothrim** [nsch0e/opencubes#21]
I'm having problems the split cache files generated:

If I understand the cache file format as of now the numPolycubes is the total number of Cubes in the file,
and they are divided into numShapes sections of cubes by shape.
This should mean that for proper cache file `numShapes` <= `numPolycubes` should *always be true*.

But this is not the case: some generated files have `numShapes` > `numPolycubes` that I think is definitely not correct.
Such cache files eventually causes the current code to *crash/segfault* when the code accesses data past end of the file.

@nsch0e  can you explain what shape(s) an split cache file should contain?

**Comment by nsch0e** [comment]
@JATothrim 
numShapes > numPolycubes is possible because a shape section can be empty.
This is the case for split cache files. Each cachefile should contain ALL possible shape _headers_ for the given N, but only one contains polycubes.

**Comment by JATothrim** [comment]
> @JATothrim numShapes > numPolycubes is possible because a shape section can be empty. This is the case for split cache files. Each cachefile should contain ALL possible shape _headers_ for the given N, but only one contains polycubes.

My apologize, I have assumed wrong.
So there are saved entries that point past-end of the file and the offset is bogus if the entry size is zero.
The bogus offsets kept tripping me up, since I was expecting them to point into valid part of the file...
